title: Vincent Ifezue
description: Documenting my tech journey
author: Vincent Ifezue
logo: /hcz-jekyll-blog/static/img/avatar.png
github: https://github.com/Techyvince
about: Devops Engineer

baseurl: "https://github.com/Techyvince/Techyvince.github.io"
url: "https://github.com/Techyvince/Techyvince.github.io"

allowsearch: true

disqus_shortname:
google_analytics:

#share:
#  twitter_username: \#
#  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 5
per_page: 5
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
